### ISSUE TITLE
deploy.sh does not work with python < 3

### ISSUE THREAD

**Issue by ajm188** [hacsoc/talks#3]
Gives the following traceback:

```
Traceback (most recent call last):
  File "generate_html.py", line 83, in <module>
    render_talks(data_for_repos())
  File "generate_html.py", line 80, in render_talks
    f.write(t.render(talks=talks))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./template.html", line 20, in top-level template code
    <p><strong>Description: </strong>{{ info.description }}</p>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 24: ordinal not in range(128)
```

**Comment by thomasrussellmurphy** [comment]
^ traceback in Python 2.7, same behavior observed here.

**Comment by ajm188** [comment]
Yeah this was with 2.7.6. It happens with any python below 3.0.0.
